language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1
  - nightly

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

script:
    - export JULIA_PROJECT=""
    - julia --project -e 'using Pkg; Pkg.build();
                          Pkg.test(;coverage=true);
                          Pkg.activate(mktempdir());
                          Pkg.develop([PackageSpec(name="Revise"), PackageSpec(path=".")]);
                          VERSION >= v"1.3" && Pkg.test(; coverage=true, test_args=["revise"]);
                          Pkg.test("Revise"; coverage=true)'

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
